### PR TITLE
Adding the ability to remove a route

### PR DESCRIPTION
**Pull request by Narno**
Fixing #17

### CODE REVIEW

**Comment by Narno** [comment]
Ping @weierophinney :-)

**Comment by Narno** [comment]
Have I any chance to have a review of my proposition ? :-)

Thank you!

**Comment by RalfEggert** [comment]
+1

**Comment by weierophinney** [comment]
Why would you need it, @Narno ?

I ask, because you typically create your application iteratively; it's not something you extend. If you need to remove a route, then why did you add it in the first place?

Essentially, I want to understand the use case before merging.

**Comment by RalfEggert** [comment]
@weierophinney This is mainly about removing the default routes autocomplete, help and version. They are added in `ZF\Console\Application::__construct()` with every run if you need them or not.

**Comment by Narno** [comment]
Hello @weierophinney, as indicated by @RalfEggert, the goal is to remove the default routes and also to manage a plugin logic and so be able to remove and replace a route with another.

**Comment by weierophinney** [comment]
@Narno and @RalfEggert — thanks for the clarification!

**Comment by Narno** [comment]
Thanks a lot!

**Pull request merged**
